apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:FabioCaffarello/lakehouse-lab.git
    targetRevision: feat/nx-plugin-integration
    path: deploy/iac/tf-local/k8s/deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: testns
  syncPolicy:
    retry:
      limit: 2
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
