repos:
  # Commit linting (Conventional Commits)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.2
    hooks:
      - id: commitizen
        entry: cz check
        args: ["--allow-abort", "--"]
        stages: [commit-msg]
  # Basic code quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast # Check Python files for syntax errors
