repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.2
    hooks:
      - id: commitizen
        entry: cz check
        args: ["--allow-abort", "--"]
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-ast
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yml"]
