extends: default
rules:
  document-start: disable
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  empty-lines:
    max: 100
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
