apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  type: Z2l0Cg==
  url: Z2l0QGdpdGh1Yi5jb206RmFiaW9DYWZmYXJlbGxvL2xha2Vob3VzZS1sYWIuZ2l0Cg==
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNESWIyTG5PWjM0cWpSRWFuSWRPU3NaZDZtNzJNY1NraERJdEUrbHFsL3VSUUFBQUtESjRjU0p5ZUhFCmlRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDREliMkxuT1ozNHFqUkVhbklkT1NzWmQ2bTcyTWNTa2hESXRFK2xxbC91UlEKQUFBRURFV2FNNHloczdlbzZONHUzbXZybXRrYzVxeHpXZE1PRFh1Uk05R1VYakI4aHZZdWM1bmZpcU5FUnFjaDA1S3hsMwpxYnZZeHhLU0VNaTBUNldxWCs1RkFBQUFHbVpoWW1sdkxtTmhabVpoY21Wc2JHOUFaMjFoYVd3dVkyOXRBUUlECi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
