apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FabioCaffarello/lakehouse-lab
    targetRevision: feat/nx-plugin-integration
    path: deploy/k8s/manifests/resources/minio
  destination:
    name: 'in-cluster'
    namespace: storage
    server: ''
  syncPolicy:
    retry:
      limit: 2
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
